```{r include = FALSE}
source("./data_load.R")
source("./sampler.R")
source("./formula_builder.R")
library(dplyr)
```
# Procedure

Test all formulas (no Character type included) by learning from half the learning sample to predict the other half. As the sampling process is random, iterate 100 times each. 
```{r}
LOOP_NUMBER <- 100
FACTORS <- c("Pclass", "Sex", "Age", "SibSp", "Parch", "Fare", "Embarked")
RESPONSE_VARIABLE <- "Survived"
```
# Build all formulas
```{r}
all_formulas <- build_formulas(
    response_variable = RESPONSE_VARIABLE,
    factors = FACTORS
)

all_result <- list()
for (formula in all_formulas) {
    print(as.character(formula)[3])
    result <- c()
    for (loop_index in (1:LOOP_NUMBER)) {
        sample <- random_sampler(
            data = training,
            batch_predict_ratio = 2)

        decision_tree <- party::ctree(
            formula,
            sample$train_sample
        )
        prediction <- predict(decision_tree, sample$pred_sample)
        result <- c(result, sum(prediction == sample$pred_sample[['Survived']]) / length(sample$pred_sample[['Survived']]))
    }
    all_result[[as.character(formula)[3]]] <- result
}
```

```{r}
all_result_matrix <- sapply(all_result, function(vec) {
  return(vec)
})
all_result_mean <- colMeans(all_result_matrix)
ordering <- sort(all_result_mean, index.return = TRUE, decreasing = TRUE)
ordering$x[(1:10)]
```